### ISSUE TITLE
Trouble with Composite indexes

### ISSUE THREAD

**Issue by mathewparet** [tomwalder/php-gds#96]
I am having trouble with composite indexes.

My index.yaml reads:
```YAML
indexes:
- kind: Sources
  properties:
  - name: language
    direction: asc
  - name: modified
    direction: desc
```

I am facing the below issues:

1. On dev, it is working fine. I had to make the index.yaml manually. It wasn't auto generated. I don't understand why.
2. On prod, the same is failing with error 500. I am unable to catch exception for the code either.
3. When running the below query:

````SQL
select * from Sources where language='malayalam' order by modified desc
```
I get the below error:

> GQL query error: Your Datastore does not have the composite index (developer-supplied) required for this query.
>  Run query
